### ISSUE TITLE
WebDriver present with a remote launcher

### ISSUE THREAD

**Issue by Nexion** [go-rod/bypass#10]
I'm trying to use bypass with a remote launcher in a [docker image](https://hub.docker.com/r/rodorg/rod), but it fails the WebDriver test. Any chance I can make it work this way?

```go
func main() {
	client := launcher.MustNewRemote("ws://localhost:9222")
	client.Headless(true)

	browser := rod.New().Timeout(time.Minute*2).Client(client.Client()).MustConnect()
	...
```

**Comment by ysmood** [comment]
Use rod v0.89.3, it should be solved.
