### ISSUE TITLE
webdriver is true on the new page 

### ISSUE THREAD

**Issue by Abin01** [go-rod/bypass#2]
Click on a label to open a new page, and webdriver is true on the new page. 

What methods are there to deal with?

**Comment by ysmood** [comment]
We can add a helper to use `page.WaitOpen()` to handle it.

**Comment by NormalPunch** [comment]
> Click on a label to open a new page, and webdriver is true on the new page.
> 
> What methods are there to deal with?

You need to use `Page.addScriptToEvaluateOnNewDocument` to inject the bypass js code into each page.

And it will take effect [in every frame upon creation](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument).

**Comment by ysmood** [comment]
Example code to demo how to use `WaitForDebuggerOnStart`:

https://github.com/go-rod/rod/blob/cb480122265de530b5d919584cf60d57ce2ea726/page_test.go#L234-L254

**Comment by ysmood** [comment]
@Abin01 I add a new function to support it, the unit test shows how to use it:

https://github.com/go-rod/rod/blob/899b00ac27e25786f0a6820a35164436b24bf21c/page_test.go#L251-L265

**Comment by ysmood** [comment]
I will close it for now. If you have any problems please let us know.
